// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://whlbuzrssurjvqzqshmz.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6IndobGJ1enJzc3VyanZxenFzaG16Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTU3ODczNDgsImV4cCI6MjA3MTM2MzM0OH0.Syxm-2QzbW2Hk7gbfholluOjfk48q-bkwexwYnkVrQo";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});